### ISSUE TITLE
Add handling for send_to_modchat read timeout from requests

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor_core#17]
```
May 22 15:07:48 ADDR tor_moderator[15012]: INFO | process_post | Posting call for transcription on ID t3_8lai0m posted by mrbubblesisalie
May 22 15:08:48 ADDR tor_moderator[15012]: INFO | stop_heartbeat | Stopped heartbeat!
May 22 15:08:48 ADDR tor_moderator[15012]: ERROR | explode_gracefully | HTTPConnectionPool(host='<MODCHAT_HOSTNAME>', port=<MODCHAT_PORT>): Read timed out. (read timeout=30)
May 22 15:08:48 ADDR systemd[1]: tor_moderator.service: main process exited, code=exited, status=1/FAILURE
May 22 15:08:48 ADDR systemd[1]: Unit tor_moderator.service entered failed state.
May 22 15:08:48 ADDR systemd[1]: tor_moderator.service failed.
```

**Comment by itsthejoker** [comment]
I'm thinking we can write an Error log level message with whatever we were trying to send to modchat if it fails?

**Comment by TheLonelyGhost** [comment]
Definitely log level ERROR. The modchat notifications _should_ be fire-and-forget, however we have a bit of work to do to get it there. I'd almost wrap the `notify_modchat` method (or whatever) with the `try`-`except` logic. Gracefully degrade, and all that.

**Comment by DavidArchibald** [comment]
I don't normally chime into issues I think are going the right direction already, but I just wanted to add that informative but concise error messages are incredibly helpful for people unfamiliar with the codebase, and even the regular devs.

**Comment by Azrael-1123** [comment]
shouldn't this be closed? it's kinda confusing to see an issue there when there isn't really one anymore

**Comment by itsthejoker** [comment]
Mmm. Yeah. This is pretty old. Good catch!
